// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACRg683fVrlzrgkG8MXi7dlzmIevoz2_U',
    appId: '1:952786014191:web:8e788831facfbfcdea301a',
    messagingSenderId: '952786014191',
    projectId: 'unipay-53a9d',
    authDomain: 'unipay-53a9d.firebaseapp.com',
    databaseURL: 'https://unipay-53a9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unipay-53a9d.appspot.com',
    measurementId: 'G-H3WBY9KVZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpU_BINUppmeoY11nDJbLrt50TLCvRNQ',
    appId: '1:952786014191:android:d538019646f9a91cea301a',
    messagingSenderId: '952786014191',
    projectId: 'unipay-53a9d',
    databaseURL: 'https://unipay-53a9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unipay-53a9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnEUvQJg4wdkB6gGdrrCtgLSY1W8IdJsA',
    appId: '1:952786014191:ios:b47df969fe5da16aea301a',
    messagingSenderId: '952786014191',
    projectId: 'unipay-53a9d',
    databaseURL: 'https://unipay-53a9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unipay-53a9d.appspot.com',
    iosBundleId: 'com.example.unipay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnEUvQJg4wdkB6gGdrrCtgLSY1W8IdJsA',
    appId: '1:952786014191:ios:0a24bd11ad581b46ea301a',
    messagingSenderId: '952786014191',
    projectId: 'unipay-53a9d',
    databaseURL: 'https://unipay-53a9d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unipay-53a9d.appspot.com',
    iosBundleId: 'com.example.unipay.RunnerTests',
  );
}
